# Shell variables
# Generated by 'wal'
wallpaper='/home/piyush/wallpapers/3.jpg'

# Special
background='#16101b'
foreground='#deafbd'
cursor='#deafbd'

# Colors
color0='#16101b'
color1='#91567B'
color2='#BF556B'
color3='#A66376'
color4='#676987'
color5='#955C81'
color6='#A56586'
color7='#deafbd'
color8='#9b7a84'
color9='#91567B'
color10='#BF556B'
color11='#A66376'
color12='#676987'
color13='#955C81'
color14='#A56586'
color15='#deafbd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
