# Shell variables
# Generated by 'wal'
wallpaper='/home/piyush/wallpapers/john-towner-JgOeRuGD_Y4-unsplash.jpg'

# Special
background='#04060C'
foreground='#b3bac7'
cursor='#b3bac7'

# Colors
color0='#04060C'
color1='#4A586F'
color2='#536179'
color3='#923B4A'
color4='#3F5F86'
color5='#596986'
color6='#687691'
color7='#b3bac7'
color8='#7d828b'
color9='#4A586F'
color10='#536179'
color11='#923B4A'
color12='#3F5F86'
color13='#596986'
color14='#687691'
color15='#b3bac7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
