# Shell variables
# Generated by 'wal'
wallpaper='/home/piyush/wallpapers/G4QrX1H.png'

# Special
background='#0d0a1e'
foreground='#e699cd'
cursor='#e699cd'

# Colors
color0='#0d0a1e'
color1='#E83372'
color2='#54228F'
color3='#5D2391'
color4='#2A55B2'
color5='#A02FA7'
color6='#D32C98'
color7='#e699cd'
color8='#a16b8f'
color9='#E83372'
color10='#54228F'
color11='#5D2391'
color12='#2A55B2'
color13='#A02FA7'
color14='#D32C98'
color15='#e699cd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
